language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DEPS=latest
  - DEPS=lowest

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-lowest ; fi

script:
  - composer test:units

jobs:
  include:
    - stage: test
      name: 'Lint Syntax'
      php: 7.4
      script:
        - composer lint:syntax
    - stage: test
      name: 'Lint Style'
      php: 7.4
      script:
        - composer lint:style
    - stage: test
      name: 'Coverage'
      php: 7.4
      script:
        - composer test:coverage
    - stage: test
      name: 'Mutations'
      php: 7.4
      script:
        - composer require --dev infection/infection
        - composer test:mutations
    - stage: test
      name: 'Integration, DEPS=LATEST'
      php: 7.4
      script:
        - cd test/integration
        - composer install --no-interaction
        - vendor/bin/phpunit
    - stage: test
      name: 'Integration, DEPS=LOWEST'
      php: 7.4
      script:
        - cd test/integration
        - composer update --prefer-lowest --no-interaction
        - vendor/bin/phpunit

notifications:
  email: false
