language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  - DEPS=latest
  - DEPS=lowest

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-lowest ; fi

script:
  - composer test:units

jobs:
  allow_failures:
    - php: 7.4snapshot
  include:
    - stage: test
      php: 5.3
      dist: precise
      env: DEPS=latest
      script:
        - composer update --no-interaction --prefer-source
        - composer test:units
    - stage: test
      php: 5.3
      dist: precise
      env: DEPS=lowest
      script:
        - composer update --no-interaction --prefer-source --prefer-lowest
        - composer test:units
    - stage: test
      name: 'Lint Syntax'
      php: 7.1
      script:
        - composer install --no-interaction --prefer-source
        - composer lint:syntax
    - stage: test
      name: 'Lint Style'
      php: 7.1
      script:
        - composer install --no-interaction --prefer-source
        - composer lint:style
    - stage: test
      name: 'Coverage'
      php: 7.1
      script:
        - composer install --no-interaction --prefer-source
        - composer test:coverage
    - stage: test
      name: 'Mutations'
      php: 7.1
      script:
        - composer install --no-interaction --prefer-source
        - composer require --dev infection/infection
        - composer test:mutations
    - stage: test
      name: 'ZF2 Integration'
      php: 5.6
      script:
        - cd test/ZF2
        - composer install --no-interaction --prefer-source
        - vendor/bin/phpunit
    - stage: test
      name: 'ZF3 Integration'
      php: 5.6
      script:
        - cd test/ZF3
        - composer install --no-interaction --prefer-source
        - vendor/bin/phpunit

notifications:
  email: false
